apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: marketflow
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
  PRODUCT_DB_PASSWORD: product_pass
  ORDER_DB_PASSWORD: order_pass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: marketflow
data:
  init.sql: |
    CREATE USER product_user WITH PASSWORD 'product_pass';
    CREATE DATABASE product_db OWNER product_user;
    CREATE USER order_user WITH PASSWORD 'order_pass';
    CREATE DATABASE order_db OWNER order_user;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: marketflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: init-script
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: marketflow
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
