server.port=8082

# Banco PROPRIO do servico de produtos (PostgreSQL, acesso reativo via Spring Data R2DBC)
spring.r2dbc.url=r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/produtos_db
spring.r2dbc.username=produtos_user
spring.r2dbc.password=produtos_pass
